### ISSUE TITLE
mainpage.php?miner= ???

### ISSUE THREAD

**Issue by 200787128** [karek314/ethereum-mining-pool-php#20]
$data_redit = array("id" => 73, "jsonrpc" => "2.0", "result" => true);                                                                    
$data_string_redit = json_encode($data_redit);
echo $data_string_redit;

ethminer -G -F http://domain/?miner=10@0x752023bfdc09d80a2a6df66101a71f04d1d24083@OptionalRigName

{"id":73,"jsonrpc":"2.0","result":true}

JSON-RPC problem. Probably couldn't connect. Retrying 

$data_redit = array("id" => 73, "jsonrpc" => "2.0", "result" => true);    ????

**Comment by karek314** [comment]
Check their api, i guess something changed causing this issue.
