### ISSUE TITLE
How to update the latest block?

### ISSUE THREAD

**Issue by 200787128** [karek314/ethereum-mining-pool-php#22]
![image](https://user-images.githubusercontent.com/29242983/27429858-35575a78-5779-11e7-9112-d57b39ff803c.png)

How to update the latest block?

**Comment by 200787128** [comment]
![image](https://user-images.githubusercontent.com/29242983/27463616-58aa6574-57fb-11e7-9837-dfaa81b40d9a.png)
new block is 3915713  ?why my is 1 2 3

**Comment by karek314** [comment]
You should check your ethereum node and if it's fine, issue might be in ethereum node api changes. (this repository is no longer maintained, it has been developed in very early stage of ethereum, some things might have changed), however if you locate issue, feel free to pr.
