### ISSUE TITLE
Getting work package .. never gets work package

### ISSUE THREAD

**Issue by lordachoo** [karek314/ethereum-mining-pool-php#23]
Few questions - I typically don't post on here but I spent time getting this going and appear close.. (hopefully..) 

I believe i have everything up and running for the most part.

When i connect it never gives the worker a work package.

You can see in /var/log/nginx/access.log that it's just submitting the URL

IP_ADDRESS - - [02/Jul/2017:01:15:02 +0000] "POST /?miner=1@0xXXXXXXXXXXX HTTP/1.1" 200 125 "-" "-"

I haven't started checking, but any ideas why it wouldn't be giving out work packages?

Maybe there needs to be additional nginx settings for the doc_root that i'm missing?

-------------

Also, in the documentation it mentions :

curl http://127.0.0.1:9846/check/

What is supposed to be running on port 9846?

And finally,

For pyethereum , i installed it, but i'm not sure what it does or what accesses it.

**Comment by lordachoo** [comment]
I turned on logging

its eth_getWork repeatedly and eth_submitHashrate :

```
---------------------------New Query
Method:eth_submitHashrate From IP:x
User Hashrate S:12mhash
User payout S:0x04A85782F062B1b958aa6E930802F47C802Ca41C

TIME DIFF:0

Response:



---------------------------New Query
Method:eth_getWork From IP:x
User Hashrate S:12mhash
User payout S:0x04A85782F062B1b958aa6E930802F47C802Ca41C

LAST BLOCK Diff: / 0
LAST BLOCK Time:0
LAST BLOCK Time:1498960492s

Respons1:
Fixed diff value:180000000
APPKEY:cc658a9f9aff508d0565b1226d9ef9a3
Target:0x00000017dc65dee09bce86b17765627244914164f564fafca2dcdf8163e8f580

Respons2:{"id":1,"jsonrpc":"2.0","result":[null,null,"0x00000017dc65dee09bce86b17765627244914164f564fafca2dcdf8163e8f580"]}



---------------------------New Query
Method:eth_submitHashrate From IP:x
User Hashrate S:12mhash
User payout S:0x04A85782F062B1b958aa6E930802F47C802Ca41C

TIME DIFF:1

Response:



---------------------------New Query
Method:eth_getWork From IP:x
User Hashrate S:12mhash
User payout S:0x04A85782F062B1b958aa6E930802F47C802Ca41C

LAST BLOCK Diff: / 0
LAST BLOCK Time:0
LAST BLOCK Time:1498960493s

Respons1:
Fixed diff value:180000000
APPKEY:cc658a9f9aff508d0565b1226d9ef9a3
Target:0x00000017dc65dee09bce86b17765627244914164f564fafca2dcdf8163e8f580

Respons2:{"id":1,"jsonrpc":"2.0","result":[null,null,"0x00000017dc65dee09bce86b17765627244914164f564fafca2dcdf8163e8f580"]}
```

**Comment by lordachoo** [comment]
I fixed the work issue..was block processing not working properly. 

Looks like things are working now. Still curious on nginx config, if i should do a location for /check/ , and pyethereum, though.

**Comment by lordachoo** [comment]
Last issue..hopefully.. :) 

When submitting work, it's never accepted. Which process should I be looking at for troubleshooting that?

**Comment by lordachoo** [comment]
Getting expired times -- i updated the time on the server with ntp and it's correct now. 

---------------------------New Query
Method:eth_submitWork From IP:xxx
User Hashrate S:2mhash
User payout S:0x04A85782F062B1b958aa6E930802F47C802Ca41C
\Work:{"id":1,"jsonrpc":"2.0","method":"eth_submitWork","params":["0x7ff0d533fd9d3ab7","0xda6d48f6a7b852cc68124218c4965fa68688fc904ac3a2f4ba18412e72d3133a","0x4d9ea742d91dd43f767e095c313d34c693468f173137461d1df7f54c95082d60"]}


Response:{"jsonrpc":"2.0","id":1,"result":false}

===========WORK HAS NOT BEEN SUMBITED DUE EXPIRED SOLUTION=============

Maybe because geth hasn't fully sync'd the blockchain yet? IT's difficult to read the code between LN388 -> LN 444 on index.php

**Comment by lordachoo** [comment]
Resolved that issue by resyncing geth -- now when a share gets submitted it doesn't respond, don't see anything logged and afterwards work doesn't get delivered (0 hash rate after it submits the results, doesn't get an RPC reply and times out)

**Comment by karek314** [comment]
To be honest with you i barely remember this code, it's was written at early stages of ethereum, seems some things has changed. If you solved those issues, feel free to pull request.

**Comment by lordachoo** [comment]
```
/usr/bin/python /root/pyethereum/ethereum/nonce_fast.py
Traceback (most recent call last):
  File "/root/pyethereum/ethereum/nonce_fast.py", line 2, in <module>
    import ethpow
  File "/root/pyethereum/ethereum/ethpow.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ethereum-2.0.4-py2.7.egg/ethereum/pow/__init__.py", line 1, in <module>
    from ethereum.pow import chain, consensus, ethash, ethash_utils, ethpow
  File "/usr/local/lib/python2.7/dist-packages/ethereum-2.0.4-py2.7.egg/ethereum/pow/chain.py", line 7, in <module>
    from ethereum.meta import apply_block
  File "/usr/local/lib/python2.7/dist-packages/ethereum-2.0.4-py2.7.egg/ethereum/meta.py", line 4, in <module>
    from ethereum.common import mk_block_from_prevstate, validate_header, \
  File "/usr/local/lib/python2.7/dist-packages/ethereum-2.0.4-py2.7.egg/ethereum/common.py", line 10, in <module>
    from ethereum.messages import apply_transaction
  File "/usr/local/lib/python2.7/dist-packages/ethereum-2.0.4-py2.7.egg/ethereum/messages.py", line 20, in <module>
    from ethereum.specials import specials as default_specials
  File "/usr/local/lib/python2.7/dist-packages/ethereum-2.0.4-py2.7.egg/ethereum/specials.py", line 2, in <module>
    from py_ecc.secp256k1 import privtopub, ecdsa_raw_recover, N as secp256k1n
ImportError: cannot import name N

```

**Comment by karek314** [comment]
Did you tried to install it following instructions ?
https://github.com/ethereum/pyethereum

**Comment by karek314** [comment]
https://github.com/karek314/ethereum-mining-pool-php/blob/master/block_processing/index.php#L261

Simply call it with file path and random number

**Comment by lordachoo** [comment]
Yeah, that's what i was afraid of ..i still get this , i am following the instructions for pyethereum install 

`/usr/bin/python /root/pyethereum/ethereum/nonce_fast.py '/var/www/block_processing/temp.txt' '2534'`

returns

```
Traceback (most recent call last):
  File "/root/pyethereum/ethereum/nonce_fast.py", line 2, in <module>
    import ethpow
ImportError: No module named ethpow

```

**Comment by karek314** [comment]
What comes to my mind is that you can try with previous version of pyethereum repository (like one year ago), not really sure what they've changed. Another solution to this is using command line to verify it though it's much, much slower than **nonce_fast.py**.

**Comment by lordachoo** [comment]
I'll try both -- 

I'll try and figure it out, but what would the command line to test it via geth RCP call?

when i looked it didn't seem like all the parameters were the same - i can't find where in index.php it pushes anything to block_processing/index.php -- which is the only place that nonce_fast.py gets called

**Comment by lordachoo** [comment]
It's working (it executes at least...) on v1.4.0

```
root@ubuntu-1gb-sfo1-01:~/pyethereum-1.4.0/ethereum# /usr/bin/python ./nonce_fast.py /var/www/block_processing/temp.txt 2345
Creating 2 threads
I:0 Nonce:353cd383bfe9557e=True

```

**Comment by lordachoo** [comment]
Still getting rejected work -- I think the rejection is before this, although i don't totally understand how/when the nonce gets verified.

It seems like

Index.php receives submit_getwork -> index.php does rcp call to geth to get work packet  -> index.php sends json work packet to miner -> miner mines, finds solution, sends submitwork to index.php -> index.php goes through that long set of conditionals, sends the packet of work to geth via RCP submitWork -> Geth sends back false

all of this is shown in the logs, so i don't think it ever touches block_processing yet, right? it looks like if geth returned TRUE on the submitWork portion the conditionals would keep going, and the nonce info calculated in block_processing would be pulled from memcache (put there by block_processing/index.php) and things would keep going from there -- but it gets stopped before it even gets to this process.

I'm not sure why the data from miner would be invalid, everything seems to be working.

**Comment by karek314** [comment]
> sends the packet of work to geth via RCP submitWork -> Geth sends back false

This happens because what we are sending from pool to miners is target with lowered difficulty. Hence miner is able to find solutions faster but not always solution is found block, it's called "share". We need to send each solution found as soon as possible to geth to claim found solution before others, this is why you are getting false, you should get false from geth unless solution is valid for current real target.

block_processing/index.php - Is verifying is splitting accordingly if block has been found and then shares are being verified. Reason why we need to call nonce_fast.py is because dishonest miner can manipulate difficulty of share and send shares much more often and generate additional balance for work which simply has not been done. nonce_fast.py is verifying proof of work job sumitted by miners (if difficulty match one we sent).

**Comment by gbtota** [comment]
for new version of pythereum replace the import ethpow import with:
from ethereum.pow import ethpow
