### ISSUE TITLE
Get Work -> Submit Solution Invalid

### ISSUE THREAD

**Issue by lordachoo** [karek314/ethereum-mining-pool-php#24]
Posting here in order to hopefully help others if i get a solution it'll be documented w/ the logstate outputs.

Geth is completely sync'd now (was my fault before thinking it would sync without being a complete pain...) -- still getting rejected solutions -- as far as i can tell this is all related to the process that is handled in the main index.php

Index.php -> GetWork via RPC Call to Geth -> Sends to miner -> Miner solves -> Sends back to index.php -> index.php sends eth_submitWork to geth via RPC -> Geth rejects solution

So it wouldn't have anything to do with pyethereum yet? Or am i missing something?

Any idea why the work being sent out -> solution would be invalid 100% of the time ?

Example:

```
---------------------------New Query
Method:eth_getWork From IP:xx
User Hashrate S:41mhash
User payout S:0x04A85782F062B1b958aa6E930802F47C802Ca41C

LAST BLOCK Diff:0x39be42cc2a390 / 1015829235934096
LAST BLOCK Time:1499147975
LAST BLOCK Time:36s

Respons1:{"jsonrpc":"2.0","id":73,"result":["0x46998d6ad6d2f7124b38f5ec0417da7c953770a460caecbd4e6ea26bd859c472","0x39c5f107628ba618a6a867dd78baf80d6d04ace84c3835886f198872e48f084a","0x00000000000046ecd6f7b0de7e6d7885a284870a456aabccb5e05d49be919720"]}

Fixed diff value:2460000000
APPKEY:29d3c33845d889f57665b7b58ae98308
Target:0x00000001bef4b8e4ba3ad1a915395e9e36f7e590c0c8f325379fc56d5eb9a192

Respons2:{"id":1,"jsonrpc":"2.0","result":["0x46998d6ad6d2f7124b38f5ec0417da7c953770a460caecbd4e6ea26bd859c472","0x39c5f107628ba618a6a867dd78baf80d6d04ace84c3835886f198872e48f084a","0x00000001bef4b8e4ba3ad1a915395e9e36f7e590c0c8f325379fc56d5eb9a192"]}
```

returns as an incorrect solution::

```
---------------------------New Query
Method:eth_submitWork From IP:xxx
User Hashrate S:41mhash
User payout S:0x04A85782F062B1b958aa6E930802F47C802Ca41C
\Work:{"id":1,"jsonrpc":"2.0","method":"eth_submitWork","params":["0xa46fa902d1fba324","0x042a88a633717200c29ba3eba409bdc252b18f9c8aee4dd04cd3870de2db5bbb","0x0f0d01b9320762cbd43ef0257de77bfe76396fb30285c1c1ac0143ad0951c85b"]}

Response:{"jsonrpc":"2.0","id":1,"result":false}

===========WORK HAS NOT BEEN SUMBITED DUE EXPIRED SOLUTION=============

```

**Comment by bcmonster** [comment]
I ran into this a couple months ago.   I think that it has something to do with the formula template being out of date.   I reached out tot the guys still running this front end but got no response.

**Comment by lordachoo** [comment]
Hi @bcmonster ,

Hmm, formula template where?

the JSON RPC Response or something else?

I'm trying to figure out if this ever touches block_processing and i don't think it does since it never gets past the eth_submitWork portion in the primary index.php -- there's not much formula there, simply serves out work, gets work back then geth says its invalid.

**Comment by lordachoo** [comment]
It gets further , i still got the same error on the miner side,

i set $logstate to true -- digging in deeper now, posting this in parallel

```
---------------------------New Query
Method:eth_submitWork From IP:98.210.99.2
User Hashrate S:41mhash
User payout S:0x04A85782F062B1b958aa6E930802F47C802Ca41C
\Work:{"id":1,"jsonrpc":"2.0","method":"eth_submitWork","params":["0xec6b973e8a398ee9","0x90e0f613056f94f9b4c0cb7c10ba9ffb46b26fc3b3966747c5b00f4a20458137","0x47d1c5816656b70a85c9c38c33bc6cc13eee380b6bd242ea29e573b5964c7b6c"]}


Response:{"jsonrpc":"2.0","id":1,"result":false}

APPKEY:29d3c33845d889f57665b7b58ae98308
==========================================================================
=======================WORK HAS BEEN SUMBITED=============================
User:0x04A85782F062B1b958aa6E930802F47C802Ca41C
UserDiff:0x00000006fbd2e392e8eb46a454e57a78dbdf96430323cc94de7f15b57ae6864b
DiffDecimal:615000000
BlockDiff:1045455706573731
BlockPowHash:0x90e0f613056f94f9b4c0cb7c10ba9ffb46b26fc3b3966747c5b00f4a20458137
RealBlockTarget:0x00000000000044ea5f70055fd3f6bedf2115bfde9092941a875edb034bebbc52
SeedHash:0x39c5f107628ba618a6a867dd78baf80d6d04ace84c3835886f198872e48f084a
Block Number:3975155 / 60248405
==========================================================================
NonceFound:0xec6b973e8a398ee9
PowHash:0x90e0f613056f94f9b4c0cb7c10ba9ffb46b26fc3b3966747c5b00f4a20458137
MixDigest:0x47d1c5816656b70a85c9c38c33bc6cc13eee380b6bd242ea29e573b5964c7b6c
==========================================================================
==========================================================================
```

**Comment by lordachoo** [comment]
I'm getting these from geth at the same time, so something is invalid still :

`WARN [07-04|16:29:43] Invalid proof-of-work submitted          hash=b5a9e6…9a7ccc err="invalid proof-of-work"
`

**Comment by lordachoo** [comment]
So I guess block_processing just updates SQL etc? right?

and process_work loads up work for index.php to pass out to the miners?

I tested with eth_submitWork and it's just giving out the result:false json for the results the miner passes back with the nonce, powhash, digestmix that the miner returns.

- I checked and geth is definitely up-to-date
- I checked the python bit with pyethereum, it should be working, but i guess that's just used to invalidate shares on the SQL/server-side right?-- although it's not invalidating the invalid shares the miner is passing back..it's inserting them into the valid shares sql table and counting them as valid..???

So the root cause should be something very simple from the very early getWork RPC call i would think... Kind of out of ideas again.

**Comment by karek314** [comment]
This will fix false positive message sent to miner -> https://github.com/karek314/ethereum-mining-pool-php/commit/78fccef37ac5afaa5f1bc15d80c1851ed3970529

This is normal unless submitted solution is valid block -> 

> WARN [07-04|16:29:43] Invalid proof-of-work submitted hash=b5a9e6…9a7ccc err="invalid proof-of-work"

**Comment by lordachoo** [comment]
Confirmed, working now! thanks!

**Comment by bcmonster** [comment]
Awesome!

Sent from my iPhone

On Jul 5, 2017, at 2:09 AM, lordachoo <notifications@github.com<mailto:notifications@github.com>> wrote:


Confirmed, working now! thanks!

**Comment by karek314** [comment]
Glad it's ok now :)

**Comment by bcmonster** [comment]
Ok.  So I started dabeling with this again.    The miner is now showing valid while geth is showing invalid.    Is that normal?

**Comment by karek314** [comment]
Yes, geth will show invalid until solution found is correct for current height. If you want more details, read this thread from beginning.

**Comment by bcmonster** [comment]
Stupid question but is pythereum still a necessity?

**Comment by karek314** [comment]
As always, just ethpow.py. Actually, this code should be taken from their c++ library and bundled as module into php, that would be best solution.
