### ISSUE TITLE
about Stratum Protocol

### ISSUE THREAD

**Issue by ibraheemhsn** [karek314/ethereum-mining-pool-php#25]
Hello 
first of all, I am sorry to posting this question in the issues section.
 I am working on developing a miner software.
I just have a question on the work flow of Stratum Protocol.
lets see the details of how miner get jobs and calculate the solution and submit the share.
 
https://slushpool.com/help/manual/stratum-protocol#how
as you know the miner will concatenate Coinb1 + Extranonce1 + Extranonce2 + Coinb2 together on the process of getting finding solutions.

NOW : I am working on developing a miner software.
lets have a look at the parameter "Extranonce1", this parameter is sent by the pool, and the miner will use it in the job. 
but I want my miner does not obey to use this Extranonce1 sent by pool !!! 
I want to use my own Extranonce1  generated by my miner !!!! 

will pool accept submitted shares includes  Extranonce1 not specified by the pool ?

if you ask why I should use Extranonce1  calculated by my miner , not Extranonce1  nominated by pool ? 
because this helps me to find solutions more quickly !!! no more details at this time :)

I read somewhere that Stratum can allow miner to choose his own Extranonce1 using this method :
mining.subscribe("user agent/version", "extranonce1")
can I use the following method to achieve my aim
mining.set_extranonce

I am looking for you your response.
Best Regards

**Comment by karek314** [comment]
HI @ibraheemhsn,
That's fine to post question in issues, no problem with that.

Bitcoin and Ethereum are quite different. It is possible to generate mining target locally, but afaik, since this pool sends dynamic difficulty, solutions may get rejected. The best solution is simply to use websockets, but i think something like such "proxy" has been already done for ethereum.

**Comment by ibraheemhsn** [comment]
### Dear @karek314
Thanks for response, 
using websockets , and **communication** workflow is not my point.
I am talking about a specific point in Stratum protocol which is **using my own Extranonce2 rather than Extranonce2 received from the pool**. 
you mentioned that : 
_"since this pool sends dynamic difficulty, solutions may get rejected."_
I will use the difficulty sent by pool and not use my own difficulty.
if you would like to reply on Extranonce2 idea above it will be helpful for me.

Thanks

**Comment by karek314** [comment]
In case this pool, i bet it won't work, most if not all shares will be rejected because difficulty is changing each time, it's auto adjusting based on interval of finding shares.

**Comment by ibraheemhsn** [comment]
Thanks @karek314  Let me try and inform you,
last question 👍  I could not fin the Stratum methods in your code 
https://en.bitcoin.it/wiki/Stratum_mining_protocol

where in your pool code can I find the methods like 
mining.extranonce.subscribe
mining.submit
mining.subscribe
etc. 

Best Regards

**Comment by karek314** [comment]
Sure, Stratum wasn't implemented to this pool. It's simple getwork only, however it's possible to quite easily adapt it.
